import {
  CF_ACCESS_DEFAULT_PROTECTED_PREFIXES,
  DEFAULT_MFA_REQUIRED_ROLES,
  DEFAULT_TRUSTED_DEVICE_DAYS,
  SESSION_TTL_ADMIN_MS,
  SESSION_TTL_OPERATOR_MS,
  SESSION_IDLE_TIMEOUT_ADMIN_MS,
  SESSION_IDLE_TIMEOUT_OPERATOR_MS,
} from "../constants.js";
import {
  SETTING_CF_ACCESS_AUD,
  SETTING_CF_ACCESS_ENABLED,
  SETTING_CF_ACCESS_PROTECTED_PREFIXES,
  SETTING_CF_ACCESS_SOURCE_PROVIDER_ID,
  SETTING_CF_ACCESS_TEAM_DOMAIN,
  SETTING_BRANDING_THEME,
  SETTING_MFA_REQUIRED_ROLES,
  SETTING_OPERATOR_SESSION_TTL,
  SETTING_SESSION_TTL,
  SETTING_SESSION_IDLE_TIMEOUT,
  SETTING_OPERATOR_SESSION_IDLE_TIMEOUT,
  SETTING_TRUSTED_DEVICE_DAYS,
  SETTING_INSTANCE_URL,
  SETTING_CSP_TRUSTED_ORIGINS,
} from "./keys.js";

/** Built-in defaults when DB and env are unset. */
export const SETTING_DEFAULTS = new Map<string, unknown>([
  [SETTING_SESSION_TTL, SESSION_TTL_ADMIN_MS],
  [SETTING_OPERATOR_SESSION_TTL, SESSION_TTL_OPERATOR_MS],
  [SETTING_SESSION_IDLE_TIMEOUT, SESSION_IDLE_TIMEOUT_ADMIN_MS],
  [SETTING_OPERATOR_SESSION_IDLE_TIMEOUT, SESSION_IDLE_TIMEOUT_OPERATOR_MS],
  [SETTING_TRUSTED_DEVICE_DAYS, DEFAULT_TRUSTED_DEVICE_DAYS],
  [SETTING_MFA_REQUIRED_ROLES, DEFAULT_MFA_REQUIRED_ROLES],
  [SETTING_CF_ACCESS_ENABLED, false],
  [SETTING_CF_ACCESS_TEAM_DOMAIN, ""],
  [SETTING_CF_ACCESS_AUD, []],
  [SETTING_CF_ACCESS_PROTECTED_PREFIXES, CF_ACCESS_DEFAULT_PROTECTED_PREFIXES],
  [SETTING_CF_ACCESS_SOURCE_PROVIDER_ID, ""],
  [SETTING_BRANDING_THEME, {}],
  [SETTING_INSTANCE_URL, null],
  [SETTING_CSP_TRUSTED_ORIGINS, []],
]);

/** Env var locks — when set, override DB value. */
export const SETTING_ENV_LOCKS = new Map<string, string>([
  [SETTING_SESSION_TTL, "SESSION_TTL_ADMIN_MS"],
  [SETTING_OPERATOR_SESSION_TTL, "SESSION_TTL_OPERATOR_MS"],
  [SETTING_SESSION_IDLE_TIMEOUT, "SESSION_IDLE_TIMEOUT_ADMIN_MS"],
  [SETTING_OPERATOR_SESSION_IDLE_TIMEOUT, "SESSION_IDLE_TIMEOUT_OPERATOR_MS"],
  [SETTING_TRUSTED_DEVICE_DAYS, "TRUSTED_DEVICE_DAYS"],
  [SETTING_MFA_REQUIRED_ROLES, "MFA_REQUIRED_ROLES"],
  [SETTING_CF_ACCESS_ENABLED, "CF_ACCESS_ENABLED"],
  [SETTING_CF_ACCESS_TEAM_DOMAIN, "CF_ACCESS_TEAM_DOMAIN"],
  [SETTING_CF_ACCESS_AUD, "CF_ACCESS_AUD"],
  [SETTING_CF_ACCESS_PROTECTED_PREFIXES, "CF_ACCESS_PROTECTED_PREFIXES"],
  [SETTING_CF_ACCESS_SOURCE_PROVIDER_ID, "CF_ACCESS_SOURCE_PROVIDER_ID"],
  [SETTING_INSTANCE_URL, "BASE_URL"],
  [SETTING_CSP_TRUSTED_ORIGINS, "CSP_TRUSTED_ORIGINS"],
]);
