import {
  DEFAULT_MFA_REQUIRED_ROLES,
  DEFAULT_TRUSTED_DEVICE_DAYS,
  SESSION_TTL_ADMIN_MS,
  SESSION_TTL_OPERATOR_MS,
} from "../constants.js";
import {
  SETTING_MFA_REQUIRED_ROLES,
  SETTING_OPERATOR_SESSION_TTL,
  SETTING_SESSION_TTL,
  SETTING_TRUSTED_DEVICE_DAYS,
} from "./keys.js";

/** Built-in defaults when DB and env are unset. */
export const SETTING_DEFAULTS: Record<string, unknown> = {
  [SETTING_SESSION_TTL]: SESSION_TTL_ADMIN_MS,
  [SETTING_OPERATOR_SESSION_TTL]: SESSION_TTL_OPERATOR_MS,
  [SETTING_TRUSTED_DEVICE_DAYS]: DEFAULT_TRUSTED_DEVICE_DAYS,
  [SETTING_MFA_REQUIRED_ROLES]: DEFAULT_MFA_REQUIRED_ROLES,
};

/** Env var locks — when set, override DB value. */
export const SETTING_ENV_LOCKS: Record<string, string> = {
  [SETTING_SESSION_TTL]: "SESSION_TTL_ADMIN_MS",
  [SETTING_OPERATOR_SESSION_TTL]: "SESSION_TTL_OPERATOR_MS",
  [SETTING_TRUSTED_DEVICE_DAYS]: "TRUSTED_DEVICE_DAYS",
  [SETTING_MFA_REQUIRED_ROLES]: "MFA_REQUIRED_ROLES",
};
